language: ruby
rvm:
- 2.2
before_install:
- gem install --no-document rubocop
notifications:
  slack:
    secure: tYeuP3ySjXHNUuZyw05somUfhG9s5HA8Acsrysnb4MOH9mTbuqdMTc59bp+BQVdFiWymtGeQwwFCagf5ZezMsT3fQBTq2tVH/kknHAj6b9Z2PANqN/4EzmpoVLuGpT5iqe+PohcLRP+QNPTwWy/uJP3Gv7oI+q7IMM4WuL6L0Tw4R9Z2Kw0uXs0C/hW2/X217adBxfRLCObXYBXF2Ffsw5iThoFzaYW/ooiroopkx14tZ9F0wu0BUsrYYteMeugF22/iDSQ9MQm7UEeOA72fjY9lW9rRStjmJOD9w+yWIGypHwRnMBkHPWnFi3TWywSNxLjMUTQZW2qfnXbFH3YDwp5lq218UEPR3G87aWWZQWJYUA2BbeeZOHmcO6uU108NZJWLqfSRddo1ptPsIkURRjUxvVUboNnayrf35UiAG24Wf5fMuLM2LP68m32QEeNhBrv2dylyjASdXDf7yxGJkSBEHPmsKzN7eY3YWknEQo4NdPgvRhEO8DU8uawWL8mQgpb5Ww7+7LVGQenjF4IV6Emri/QL7bNMsWZMkd+2llTWScCzR4Xo0ewWFmJsY2h7FZVH8EDFFHlf0VhlQlk0X0QkxmGoK33YL4XMyiVbuTBVIGEd8r0EJ48jztBEvXMysTqYtjt8i4lczl2LL+5og7/LrSTac8ODrHg7fLydjeA=
